version: '3'
services:
  app:
    image: beginner090902/aniworld_scraper_fork:latest
    volumes:
      - /your/path/on/your/maschine:/app/output
    ports:
      - "5555:5000"
    restart: unless-stopped